// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: gateway/gateway.proto

package gatewaypb

import (
	context "context"
	booking "github.com/tech-and-avinash/go-shared-ms-poc/api/proto/booking"
	event "github.com/tech-and-avinash/go-shared-ms-poc/api/proto/event"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_ProxyEventService_FullMethodName   = "/gateway.GatewayService/ProxyEventService"
	GatewayService_ProxyBookingService_FullMethodName = "/gateway.GatewayService/ProxyBookingService"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	ProxyEventService(ctx context.Context, in *event.GetEventRequest, opts ...grpc.CallOption) (*event.GetEventResponse, error)
	ProxyBookingService(ctx context.Context, in *booking.GetBookingRequest, opts ...grpc.CallOption) (*booking.GetBookingResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) ProxyEventService(ctx context.Context, in *event.GetEventRequest, opts ...grpc.CallOption) (*event.GetEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(event.GetEventResponse)
	err := c.cc.Invoke(ctx, GatewayService_ProxyEventService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ProxyBookingService(ctx context.Context, in *booking.GetBookingRequest, opts ...grpc.CallOption) (*booking.GetBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(booking.GetBookingResponse)
	err := c.cc.Invoke(ctx, GatewayService_ProxyBookingService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	ProxyEventService(context.Context, *event.GetEventRequest) (*event.GetEventResponse, error)
	ProxyBookingService(context.Context, *booking.GetBookingRequest) (*booking.GetBookingResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) ProxyEventService(context.Context, *event.GetEventRequest) (*event.GetEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyEventService not implemented")
}
func (UnimplementedGatewayServiceServer) ProxyBookingService(context.Context, *booking.GetBookingRequest) (*booking.GetBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyBookingService not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_ProxyEventService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(event.GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ProxyEventService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ProxyEventService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ProxyEventService(ctx, req.(*event.GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ProxyBookingService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(booking.GetBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ProxyBookingService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ProxyBookingService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ProxyBookingService(ctx, req.(*booking.GetBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProxyEventService",
			Handler:    _GatewayService_ProxyEventService_Handler,
		},
		{
			MethodName: "ProxyBookingService",
			Handler:    _GatewayService_ProxyBookingService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/gateway.proto",
}
