version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--providers.docker"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yaml:/etc/traefik/traefik.yaml"
      - "./traefik/dynamic:/etc/traefik/dynamic"
    networks:
      - backend

  event-service:
    build:
      context: ../..
      dockerfile: ./deployments/docker/Dockerfile.event
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.event-service.rule=Host(`localhost`) && PathPrefix(`/v1/events`)"
      - "traefik.http.services.event-service.loadbalancer.server.port=50051"

  booking-service:
    build:
      context: ../..
      dockerfile: ./deployments/docker/Dockerfile.booking
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booking-service.rule=Host(`localhost`) && PathPrefix(`/v1/bookings`)"
      - "traefik.http.services.booking-service.loadbalancer.server.port=50052"

  gateway-service:
    build:
      context: ../..
      dockerfile: ./deployments/docker/Dockerfile.gateway
    ports:
      - "8081:8080"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`localhost`) && PathPrefix(`/v1`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"

networks:
  backend:
